workflow

name: Inspection

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.organization=kuylah4503 
          -Dsonar.projectKey=kuylah4503_tubes
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
